version: '3'

services:

        # BDD contenant les donnees de ORY HYDRA 
        postgres:
                image: postgres:9.6
                container_name: hydra-postgres
                restart: always
                environment:
                        - POSTGRES_USER=hydra
                        - POSTGRES_DB=hydra
                        - POSTGRES_PASSWORD=hydra
                ports:
                        - "5432:5432"
                volumes:
                        - "pgdata:/var/lib/postgresql/data:rw"

        # Container jouant le script de création et de migration de version de la base de donnée
        hydra-migrate:
                image: oryd/hydra:v1.0.0-beta.4
                container_name: hydra-migrate
                restart: on-failure
                depends_on:
                        - postgres
                links:
                        - postgres:postgres
                environment:
                        - LOG_LEVEL=info
                        - HYDRA_SYSTEM_SECRET=juc^n+e`vZ'v,3P)
                command:
                       migrate sql postgres://hydra:hydra@postgres:5432/hydra?sslmode=disable

        hydra:
                image: oryd/hydra:v1.0.0-beta.4
                container_name: hydra
                depends_on:
                        - hydra-migrate
                restart: always
                links:
                        - postgres:postgres



# Gestion des volumes, les volumes sont externes pour être réutilisable                
volumes:
        pgdata:
            external:
                name: hydra-postgres 
